const WA="5585989446456";
const DELIVERY_FEES={"Serrinha":3,"Itaperi":4,"Dendê":4,"Parangaba":5,"Vila Peri":6,"Maraponga":6,"Jardim Cearense":6,"Passaré":7,"Boa Vista":7};
const brl=v=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function send(m){window.open(`https://wa.me/${WA}?text=${encodeURIComponent(m)}`,"_blank","noopener")}
document.querySelectorAll("[data-msg]").forEach(x=>x.onclick=()=>send(x.dataset.msg));
const pg=document.querySelector("#pizzaGrid");let active="all";let cart=JSON.parse(localStorage.getItem("dc_cart_v4")||"[]");let selected=null,selectedQty=1,mode="whole",selectedAdds=[];
function render(){let q=document.querySelector("#search").value.toLowerCase();pg.innerHTML="";PRODUCTS.filter(p=>(active==="all"||p[4]===active)&&(`${p[1]} ${p[2]}`.toLowerCase().includes(q))).forEach(p=>{let e=document.createElement("article");e.className="card";e.innerHTML=`<span class="num">${p[0]}</span><h3>${p[1]}</h3><p>${p[2]}</p><div class="bottom"><span class="price">${brl(p[3])}</span><button>ESCOLHER</button></div>`;e.querySelector("button").onclick=()=>openProduct(p);pg.appendChild(e)})}
render();document.querySelector("#search").oninput=render;document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");active=b.dataset.filter;render()});
function small(target,arr){document.querySelector(target).innerHTML=arr.map((x,i)=>`<article class="smallCard"><div><b>${x[0]}</b><span>${brl(x[1])}</span></div>${target==="#drinkGrid"?`<button class="miniAdd" data-i="${i}">+</button>`:""}</article>`).join("");if(target==="#drinkGrid")document.querySelectorAll("#drinkGrid .miniAdd").forEach(b=>b.onclick=()=>addSimple(DRINKS[+b.dataset.i][0],DRINKS[+b.dataset.i][1]))}small("#drinkGrid",DRINKS);small("#additionalGrid",ADDITIONALS);
const overlay=document.querySelector("#overlay"),drawer=document.querySelector("#cartDrawer");function openDrawer(){drawer.classList.add("open");overlay.classList.add("show");renderCart()}function closeDrawer(){drawer.classList.remove("open");overlay.classList.remove("show")}openCart.onclick=openDrawer;mobileCart.onclick=openDrawer;closeCart.onclick=closeDrawer;overlay.onclick=closeDrawer;
function pizzaOptions(query=""){let list=PRODUCTS.filter(p=>p!==selected&&p[1].toLowerCase().includes(query.toLowerCase()));halfFlavor.innerHTML=list.map(p=>`<option value="${p[0]}">${p[1]} — ${brl(p[3])}</option>`).join("");updatePM()}
function renderBuilderAdds(){builderAdds.innerHTML=ADDITIONALS.map((a,i)=>`<label class="addCheck"><input type="checkbox" data-ai="${i}"><span>${a[0]}</span><b>${brl(a[1])}</b></label>`).join("");builderAdds.querySelectorAll("input").forEach(x=>x.onchange=()=>{selectedAdds=[...builderAdds.querySelectorAll("input:checked")].map(y=>ADDITIONALS[+y.dataset.ai]);updatePM()})}
function openProduct(p){selected=p;selectedQty=1;mode="whole";selectedAdds=[];qty.textContent=1;note.value="";pmName.textContent=p[1];pmDesc.textContent=p[2];document.querySelectorAll(".mode").forEach((b,i)=>b.classList.toggle("active",i===0));document.querySelector(".halfBlock").style.display="none";halfSearch.value="";pizzaOptions();renderBuilderAdds();updatePM();showModal("productModal")}
document.querySelectorAll(".mode").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".mode").forEach(x=>x.classList.toggle("active",x===b));document.querySelector(".halfBlock").style.display=mode==="half"?"block":"none";updatePM()});halfSearch.oninput=()=>pizzaOptions(halfSearch.value);halfFlavor.onchange=updatePM;
function secondPizza(){return PRODUCTS.find(p=>p[0]===halfFlavor.value)}function basePrice(){let b=selected[3];if(mode==="half"&&secondPizza())b=Math.max(b,secondPizza()[3]);return b}function unitTotal(){return basePrice()+selectedAdds.reduce((s,a)=>s+a[1],0)}function updatePM(){if(!selected)return;pmPrice.textContent=brl(unitTotal()*selectedQty)}minus.onclick=()=>{if(selectedQty>1)selectedQty--;qty.textContent=selectedQty;updatePM()};plus.onclick=()=>{selectedQty++;qty.textContent=selectedQty;updatePM()};
addCart.onclick=()=>{let second=mode==="half"?secondPizza():null;let name=second?`Meio a meio: ${selected[1]} + ${second[1]}`:selected[1];cart.push({name,price:unitTotal(),qty:selectedQty,note:note.value,adds:selectedAdds.map(a=>a[0]),mode});save();hideModal("productModal");openDrawer()};closeProduct.onclick=()=>hideModal("productModal");
function addSimple(name,price){let f=cart.find(x=>x.name===name&&!x.note&&(!x.adds||!x.adds.length));if(f)f.qty++;else cart.push({name,price,qty:1,note:"",adds:[]});save();openDrawer()}function save(){localStorage.setItem("dc_cart_v4",JSON.stringify(cart));updateCounts()}function updateCounts(){let n=cart.reduce((s,x)=>s+x.qty,0);cartCount.textContent=n;mobileCount.textContent=n}function total(){return cart.reduce((s,x)=>s+x.price*x.qty,0)}
function renderCart(){if(!cart.length)cartItems.innerHTML='<div class="empty">Seu carrinho está vazio.<br>Escolha uma pizza no cardápio.</div>';else cartItems.innerHTML=cart.map((x,i)=>`<div class="cartItem"><div><b>${x.qty}× ${x.name}</b>${x.adds?.length?`<small>+ ${x.adds.join(", ")}</small>`:""}${x.note?`<small>Obs.: ${x.note}</small>`:""}<span>${brl(x.price*x.qty)}</span></div><button data-r="${i}">×</button></div>`).join("");cartTotal.textContent=brl(total());document.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.r,1);save();renderCart()})}updateCounts();
function showModal(id){document.querySelector("#"+id).classList.add("show")}function hideModal(id){document.querySelector("#"+id).classList.remove("show")}function deliveryFee(){if(deliveryType.value==="Retirada")return 0;let b=neighborhood.value;return Object.prototype.hasOwnProperty.call(DELIVERY_FEES,b)?DELIVERY_FEES[b]:null}function updateDelivery(){let delivery=deliveryType.value==="Entrega";document.querySelectorAll(".addressField").forEach(x=>x.style.display=delivery?"block":"none");let f=deliveryFee();deliveryFeeView.value=!delivery?"Sem taxa":(f===null?"A confirmar":brl(f));feeCheckout.textContent=!delivery?brl(0):(f===null?"A confirmar":brl(f));grandTotal.textContent=f===null?"A confirmar":brl(total()+f)}
goCheckout.onclick=()=>{if(!cart.length)return;closeDrawer();checkoutTotal.textContent=brl(total());showModal("checkoutModal");updateDelivery()};closeCheckout.onclick=()=>hideModal("checkoutModal");deliveryType.onchange=updateDelivery;neighborhood.onchange=updateDelivery;
finishWhats.onclick=()=>{let name=customerName.value.trim(),phone=customerPhone.value.trim(),type=deliveryType.value,pay=payment.value,address=window.address.value.trim(),bairro=neighborhood.value,gn=generalNote.value.trim(),fee=deliveryFee();if(!name){alert("Informe seu nome.");return}if(type==="Entrega"&&!bairro){alert("Selecione o bairro.");return}if(type==="Entrega"&&!address){alert("Informe o endereço para entrega.");return}let lines=cart.map(x=>`• ${x.qty}x ${x.name} — ${brl(x.price*x.qty)}${x.adds?.length?`\n  Adicionais: ${x.adds.join(", ")}`:""}${x.note?`\n  Obs.: ${x.note}`:""}`).join("\n");let feeText=type==="Retirada"?brl(0):(fee===null?"A confirmar":brl(fee));let finalText=fee===null?"A confirmar":brl(total()+fee);let msg=`🍕 *NOVO PEDIDO — DON CARVALHO*\n\n*Cliente:* ${name}${phone?`\n*Telefone:* ${phone}`:""}\n*Recebimento:* ${type}${type==="Entrega"?`\n*Bairro:* ${bairro}\n*Endereço:* ${address}`:""}\n*Pagamento:* ${pay}\n\n*PEDIDO*\n${lines}\n\n*Subtotal:* ${brl(total())}\n*Entrega:* ${feeText}\n*TOTAL ESTIMADO:* ${finalText}\n${gn?`\n*Observação:* ${gn}\n`:""}\nTaxa e total sujeitos à confirmação no atendimento.`;send(msg)};